name: image_gallery_from_url
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  dio: ^4.0.6
  bot_toast: ^4.0.3
  loader_overlay: ^2.0.10
  lottie: ^1.4.3
  cached_network_image: ^3.2.2
  connectivity_plus: ^2.3.7
  sqflite: ^2.1.0
  path: ^1.8.2
  uuid: ^3.0.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
